### ISSUE TITLE
UI : Previous button is not required on the page of Success message for create and update user .

### ISSUE THREAD

**Issue by RiyaMalushte** [kirmich/mustang#103]
Steps : 
1. Login
2. Go to the Users page .
3. Create user and save the details .
4. Observe the Success message and buttons at the bottom .
 
Expected : Keep only Ok tab . Remove the Previous tab .

**Comment by amitparikh-19** [comment]
started working on this.

**Comment by amitparikh-19** [comment]
Fix has been made under #109 and merged to Master.
