### ISSUE TITLE
UI : After login the right hand side logo is not responsive

### ISSUE THREAD

**Issue by RiyaMalushte** [kirmich/mustang#27]
Steps : 
1. Goto the homepage .
2. maximize the window and observe the logo .
3. Minimize the window and observe the position of the logo .

Bug : Logo is not responsive 
[http://bp.otlabspune.com/aui/#/accounts/details](url)

Expected : Logo's position should remain unchanged  when window is minimized .

**Comment by KopalD** [comment]
Duplicate issue for #25
