### ISSUE TITLE
UI : It is not showing failure message for invalid password .

### ISSUE THREAD

**Issue by RiyaMalushte** [kirmich/mustang#30]
Steps :

Goto the Sign In page .
Enter the valid username and invalid password .
Click on the Sign In .

Bug : No failure message is being dislayed for invalid password .
[http://bp.otlabspune.com/aui/#/accounts/login](url)

Expected : It should display failure message for invalid password

**Comment by tanvidev** [comment]
Hello,

Fixed an issue. Getting an error message for invalid user id or password.
