### ISSUE TITLE
UI : Change the Layout as slidedown panel is not working .

### ISSUE THREAD

**Issue by RiyaMalushte** [kirmich/mustang#31]
Steps :

1 Goto the home page .
2 Click on the General Details and then Other Details .
3 Observe the change .
4 Repeat the 2nd step .

Bug : Slidedown panel is not working .
[http://bp.otlabspune.com/aui/#/accounts/details](url)

Expected : Change the layout and make it simple like User Details .

**Comment by KopalD** [comment]
Issue has been fixed, merged code under branch #31
