### ISSUE TITLE
UI : At a time 2 alert messages are being displayed 

### ISSUE THREAD

**Issue by RiyaMalushte** [kirmich/mustang#38]
Steps :

1 Goto Users .
2 Select the user and delete it .
3 Observe the alert message .

Bug : At a time 2 alert messages are being displayed 
[http://bp.otlabspune.com/aui/#/users](url)

Expected : only one alert message should get displayed in black and white combination

**Comment by pallavivarne** [comment]
This issue is already fixed by Dipti
