### ISSUE TITLE
UI : Logo and options are overlapping when we scroll down the window

### ISSUE THREAD

**Issue by RiyaMalushte** [kirmich/mustang#39]
Steps :

1 Goto Users .
2 Minimize the window .
3 Scroll it down .
4 Observe the overlapping of logo and options .

Bug : Logo and options are overlapping when we scroll down the window
[http://bp.otlabspune.com/aui/#/users](url)

**Comment by tanvidev** [comment]
Fixed an issue, the logo will not overlap with the options.
