### ISSUE TITLE
The error/response messages not required in solid fill

### ISSUE THREAD

**Issue by pradyroy** [kirmich/mustang#48]
1. Error/Response messages box should not be solid filled
2. A black 1px rounded border is more than enough with white background of the box.
3. It has to be a component (hopefully, it already is).

It starts right away from failure message in the login/authentication failed scenario.

**Comment by KopalD** [comment]
Raised PR for this under #48

**Comment by KopalD** [comment]
PR has been merged under :
https://github.com/kirmich/mustang/pull/62
