### ISSUE TITLE
Need a component for every entity for View/Edit/Create pages

### ISSUE THREAD

**Issue by pradyroy** [kirmich/mustang#57]
Create a common component for every entity to have create, edit and view. e.g. for User:

We should have a common component, which should have an attribute/property named "write". The re can be only 2 values that "write" will take .i.e. "true" and "false".

1. For User-> Details page, we should pass on "false" as value for "write". All the fields are shown with proper labels and value fields/controls which are disabled.

2. For Create/Edit page, we should pass on "true" as value for "write". All the fields are shown with proper labels and value fields/controls enabled.

**Comment by KopalD** [comment]
Task has been completed, a common entity manager component has been added.
