### ISSUE TITLE
UI : Unwanted data is being displayed when we click on the delete button of the user details page .

### ISSUE THREAD

**Issue by RiyaMalushte** [kirmich/mustang#69]
Steps :

1 Goto User details .
2 Select the user & click on the eye symbol and view the details
3 Click on the delete button .

Bug : Some unwanted data is being displayed along with the alert message .
[http://bp.otlabspune.com/aui/#/users/details/8175765679](url)

**Comment by KopalD** [comment]
Fix is comited and merged under PR#76
