### ISSUE TITLE
UI : Bottom alignment is incorrect for Merchant Create page .

### ISSUE THREAD

**Issue by RiyaMalushte** [kirmich/mustang#75]
Steps : 
1. Go to the Users page .
2 . Click on the " + " symbol .
3 . Observe the bottom alignment 

Bug : Bottom alignment is incorrect for Merchant Create page .

Expected : Some space should be left below the buttons ( Reset , Next & Cancel ) .

**Comment by pallavivarne** [comment]
Started working on this

**Comment by pallavivarne** [comment]
Issue Fixed
