### ISSUE TITLE
 UI : Alert message of delete user is incorrect .

### ISSUE THREAD

**Issue by RiyaMalushte** [kirmich/mustang#88]
Steps :
1 Go to the users page .
2 Click on the delete button .
3 Observe the Alert message .

Bug 1 : It is displaying " delete users " in alert message when we are deleting only one user .
Expected : It should display " Delete User " .
[http://bp.otlabspune.com/aui/index.html#/users](url)

Bug 2 : It is displaying " Delete it! " .
Expected : It should be only " Delete " .
[http://bp.otlabspune.com/aui/index.html#/users](url)

**Comment by pallavivarne** [comment]
Issue fixed.
