### ISSUE TITLE
UI : Need to login everytime when we want to view the Account Details .

### ISSUE THREAD

**Issue by RiyaMalushte** [kirmich/mustang#92]
Steps : 
1. Login . Then you can see the Account Details .
2. Go to the Users page . 
3. Now look for the Account Details .

Bug : Unable to view Account Details once we visit the Users page .

Expected : Make the Home tab or logo responsive so that it would navigate to the Account Details .

**Comment by amitparikh-19** [comment]
bug has been fixed under pull request #92 and merged to Master branch.
